

# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: terraform-sa
#   namespace: ssd-tf-argocd
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: terraform-sa-admin
# subjects:
#   - kind: ServiceAccount
#     name: terraform-sa
#     namespace: ssd-tf-argocd
# roleRef:
#   kind: ClusterRole
#   name: cluster-admin
#   apiGroup: rbac.authorization.k8s.io
# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: terraform-upgrade-ssd
#   namespace: ssd-tf-argocd
#   annotations:
#     argocd.argoproj.io/hook: PostSync
#     argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
# spec:
#   backoffLimit: 0
#   template:
#     spec:
#       serviceAccountName: terraform-sa # Ensure this SA has 'cluster-admin' or 'edit' permissions
#       restartPolicy: Never
#       containers:
#         - name: terraform
#           image: hashicorp/terraform:1.6.0
#           command:
#             - /bin/sh
#             - -c
#           args:
#             - |
#               set -e
#               apk add --no-cache git bash
              
#               cd /workspace
#               git clone --branch "${TF_BRANCH}" "${TF_REPO_URL}" .
              
#               terraform init
              
#               # Try to import existing namespace if it exists to avoid 'already exists' error
#               terraform import kubernetes_namespace.opmsx_ns "${SSD_NAMESPACE}" || echo "Namespace already managed."

#               terraform apply -auto-approve \
#                 -var="git_branch=${SSD_VERSION_BRANCH}"
#           env:
#             - name: TF_REPO_URL
#               value: "https://github.com/NaveenBalagouni/argocd-terraform.git"
#             - name: TF_BRANCH
#               value: "main"
#             - name: SSD_NAMESPACE
#               value: "ssd-tf-argocd"
#           volumeMounts:
#             - name: workspace
#               mountPath: /workspace
#       volumes:
#         - name: workspace
#           emptyDir: {}



apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-sa
  namespace: ssd-tf-argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terraform-sa-admin
subjects:
  - kind: ServiceAccount
    name: terraform-sa
    namespace: ssd-tf-argocd
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-setup-ssd
  namespace: ssd-tf-argocd
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: terraform-sa
      restartPolicy: Never
      containers:
        - name: terraform
          image: hashicorp/terraform:1.6.0
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -e
              apk add --no-cache git bash

              # Clone the Terraform repo
              cd /workspace
              git clone --branch "${TF_BRANCH}" "${TF_REPO_URL}" .

              # Initialize Terraform
              terraform init

              # Apply Terraform changes
              terraform apply -auto-approve \
                -var="git_branch=${SSD_VERSION_BRANCH}"
          env:
            - name: TF_REPO_URL
              value: "https://github.com/NaveenBalagouni/argocd-tf-intern.git"       # <--- Set your Terraform repo URL
            - name: TF_BRANCH
              value: "main"   # branch to use
            - name: SSD_VERSION_BRANCH
              value: "2025-05"  # version variable for Terraform
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      volumes:
        - name: workspace
          emptyDir: {}
